#!/usr/bin/env bash

## Format usb drive

dev="$1"

[[ -b "$dev" ]] || dev="/dev/$1"

[[ -b "$dev" ]] || {
    echo "Please provide usb device."
    exit 1
}

echo "Formatting device: '$dev'."

echo -n "Erase data? [y/N]:"
read choice

if [ "$choice" = "y" ]; then
    echo "Erasing data..."
    sudo dd if=/dev/zero of="$dev" bs=1M status=progress 
fi

echo "Initializing FAT32 file system"
sudo mkfs.vfat -F 32 "$dev"
