#!/usr/bin/env bash

# Syncronize all config repos

sync_repo () {
    path=$1
    echo "Syncing repo: '$path'..."
    git -C "$path" pull --rebase && \
        git -C "$path" push
}

sync_repo "$HOME/.config/nvim" &
sync_repo "$HOME/.config/home-manager"

sleep 1
echo -e "done."
