#!/usr/bin/env python3

## Run Matlab

PROGRAM = "matlab"

from pathlib import Path
import tomllib
from subprocess import run
import sys

CONFIG_PATH = Path.home() / ".config" / PROGRAM / "config.toml"

if not CONFIG_PATH.exists():
    print(f"ERROR: config file '{CONFIG_PATH}' not found.")
    exit(1)

CONFIG = tomllib.loads(CONFIG_PATH.read_text())

cmd = CONFIG['cmd'] + " " + " ".join(sys.argv[1:])
res = run(cmd, shell=True)
exit(res.returncode)
