#!/usr/bin/env python3

## Run Vitis

from pathlib import Path
import tomllib
from subprocess import run
import sys

CONFIG_PATH = Path.home() / ".config" / "vivado" / "config.toml"

if not CONFIG_PATH.exists():
    print(f"ERROR: config file '{CONFIG_PATH}' not found.")
    exit(1)

CONFIG = tomllib.loads(CONFIG_PATH.read_text())

cmd = CONFIG['cmd']

run(cmd, check=True, capture_output=False)
